### ISSUE TITLE
Running Criticality script

### ISSUE THREAD

**Issue by danielfdsilva** [Charlesfox1/RoadAnalytics#2]
I'm interested in running the Criticality script, but while trying I ran into a couple of issues.

**Missing Modules**
I installed the needed modules by running the code, seeing the name of the missing module, installing it and repeating the process. Not sure I got all/the correct modules installed. It would be great to have a dependencies file to install the correct modules. Follows the list of modules I installed manually. There may be others needed I already had on my system.

```
ipyparallel
shapely
traitlets
zmq
SALib
spicy
ema_workbench
osmnx
networkx
geopandas
```

**Data**
The script looks for data inside the `PCS/Criticality/Vietnam_Data_Layers` but it is empty. I noticed that the script looks for the `Poverty_Communes_2009.shp`. I found these files inside `PCS/Poverty` so I copied them to `Vietnam_Data_Layers` but I'm not sure this is the correct data, and I get the following output:

```
/usr/local/lib/python2.7/site-packages/ema_workbench/em_framework/optimization.py:23: ImportWarning: platypus based optimization not available
  warnings.warn("platypus based optimization not available", ImportWarning)
Running: Criticality Analysis on YD. Do not interrupt
Traceback (most recent call last):
  File "Scripts/PCS_Criticality.py", line 334, in <module>
    main()
  File "Scripts/PCS_Criticality.py", line 122, in main
    G = net_p.gdf_to_simplified_multidigraph(gdf_node_pos, gdf, simplify=False)
  File "/guts/projects/moz-road-analysis-test/PCS/Criticality/network_lib/network_prep.py", line 336, in gdf_to_simplified_multidigraph
    G2.add_edge(u=dict_row['FNODE_'], v=dict_row['TNODE_'], **dict_row)
TypeError: add_edge() takes at least 3 arguments (1 given)
```

Any help would be appreciated.

cc @Charlesfox1 @XaviEspinet

**Comment by awa5114** [comment]
I also tried to run the criticality script and ran into the following error
```
Running: Criticality Analysis on YD. Do not interrupt

2019-01-21 11:34:25 -- ERROR: Admin boundary file requires a numerical column labelled "Pop" denoting district populations!
Traceback (most recent call last):
  File "scripts\PCS_Criticality.py", line 478, in <module>
    main()
  File "scripts\PCS_Criticality.py", line 126, in main
    prepareAdminCentroids(ginNetwork, inAdmin, crs_in, os.path.join(OD_IN, 'adm_centroids.shp'))
  File "scripts\PCS_Criticality.py", line 263, in prepareAdminCentroids
    raise ValueError("ERROR: Admin boundary file requires a numerical column labelled 'Pop' denoting district populations!")
ValueError: ERROR: Admin boundary file requires a numerical column labelled 'Pop' denoting district populations!
```

I checked the file in Vietnam_Data_Layers and indeed it is lacking the population column.

**Comment by awa5114** [comment]
I added an artificial `Pop` column to the shapefile and I am now getting the same error as you @danielfdsilva:

```
Running: Criticality Analysis on YD. Do not interrupt
Traceback (most recent call last):
  File "scripts\PCS_Criticality.py", line 478, in <module>
    main()
  File "scripts\PCS_Criticality.py", line 173, in main
    G = net_p.gdf_to_simplified_multidigraph(gdf_node_pos, gdf, simplify=False)
  File "PCS/Criticality\network_lib\network_prep.py", line 336, in gdf_to_simplified_multidig
raph
    G2.add_edge(u=dict_row['FNODE_'], v=dict_row['TNODE_'], **dict_row)
TypeError: add_edge() takes at least 3 arguments (1 given)
```
